name: Package
on: [push, pull_request]

jobs:
  package:
    strategy:
      matrix:
        os: ["macos-latest", "windows-latest", "ubuntu-latest"]
        py: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Setup Python Environment
        run: |
          pip install pyinstaller
          pip install -r requirements/requirements-generic-python3.txt
      - name: Build LabelImg
        run: |
          pyrcc5 -o libs/resources.py resources.qrc
      - name: Package LabelImg
        run: |
          pyinstaller --hidden-import=pyqt5 --hidden-import=lxml -F -n "labelImg" -c labelImg.py -p ./libs -p ./ -w
      - name: Archive macOS app
        if: startsWith(matrix.os, 'macos')
        run: |
          cd dist/
          tar czf labelImg.tgz labelImg.app
          rm -rf labelImg.app
      - name: Archive Linux app
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          cd dist/
          tar czf labelImg.tgz labelImg
          rm -rf labelImg
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: dist/labelImg.*
